<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
    <AssemblyName>VoidCrestMovesetCompat</AssemblyName>
    <RootNamespace>VoidCrestMovesetCompat</RootNamespace>
    <Authors>Erymanthis</Authors>
    <Company>ManthisCo</Company>
    <Copyright>Copyright © Erymanthis 2026</Copyright>
    <ThunderstoreProfileDir Condition="'$(ThunderstoreProfileDir)' == ''">$(APPDATA)\Thunderstore Mod Manager\DataFolder\HollowKnightSilksong\profiles\Void Playthrough</ThunderstoreProfileDir>
    <SilksongGameDir Condition="'$(SilksongGameDir)' == ''">$(MSBuildProgramFiles32)\Steam\steamapps\common\Hollow Knight Silksong</SilksongGameDir>
    <SilksongManagedDir>$(SilksongGameDir)\Hollow Knight Silksong_Data\Managed</SilksongManagedDir>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <Reference>
      <Private>false</Private>
    </Reference>
  </ItemDefinitionGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Void_Crest_Master_Thick.png"
                      LogicalName="VoidCrestMovesetCompat.Assets.Void_Crest_Master_Thick.png" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(ThunderstoreProfileDir)\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(ThunderstoreProfileDir)\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(ThunderstoreProfileDir)\BepInEx\core\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="VoidCrest">
      <HintPath>$(ThunderstoreProfileDir)\BepInEx\plugins\DerVorce-Void_Crest\VoidCrest.dll</HintPath>
    </Reference>
    <Reference Include="Needleforge">
      <HintPath>$(ThunderstoreProfileDir)\BepInEx\plugins\Voidlings-Needleforge\Needleforge.dll</HintPath>
    </Reference>
    <Reference Include="Silksong.ModMenu">
      <HintPath>$(ThunderstoreProfileDir)\BepInEx\plugins\silksong_modding-ModMenu\Silksong.ModMenu.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(SilksongManagedDir)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(SilksongManagedDir)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SilksongManagedDir)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(SilksongManagedDir)\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(SilksongManagedDir)\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(SilksongManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(SilksongManagedDir)\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(SilksongManagedDir)\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(SilksongManagedDir)\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(SilksongManagedDir)\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="PlayMaker">
      <HintPath>$(SilksongManagedDir)\PlayMaker.dll</HintPath>
    </Reference>
    <Reference Include="TeamCherry.Localization">
      <HintPath>$(SilksongManagedDir)\TeamCherry.Localization.dll</HintPath>
    </Reference>
    <Reference Include="TeamCherry.TK2D">
      <HintPath>$(SilksongManagedDir)\TeamCherry.TK2D.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(SilksongManagedDir)\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
